### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by nxskok** [loicdtx/latex2Rmd#3]
I get

Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII
Error in iconv(x[ind], "latin1", "ASCII", sub = "byte") : 
  object 'ind' not found
ERROR: installing package DESCRIPTION failed for package ‘latex2Rmd’

**Comment by nxskok** [comment]
I solved this. See the second of my pull requests.

**Comment by loicdtx** [comment]
Glad it works
